name: movie_app
description: Flutter boilerplate template for NativeWit

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  built_value: ^8.9.2
  built_collection: ^5.1.1
  intl: ^0.19.0
  rxdart: ^0.28.0

  #Utils
  package_info_plus: ^8.0.3
  device_info_plus: ^11.0.0
  share_plus: ^10.0.3
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  #image
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0

  # State
  provider: ^6.1.2
  state_notifier: ^1.0.0
  flutter_state_notifier: ^1.0.0
  logger: ^2.4.0
  collection: ^1.18.0
  go_router: ^14.3.0
  recase: ^4.1.0

  #Firebase
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  cloud_functions: ^5.1.3
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3

  stack_trace: ^1.11.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  code_builder: ^4.10.0
  dart_style: ^2.3.7
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  go_router_builder: ^2.7.1
  shelf_static: ^1.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
  shelf: ^1.4.1
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
    - assets/image7.jpg
    - assets/image8.jpg
    - assets/image9.jpg
    - assets/cast1.jpeg
    - assets/cast2.jpeg
    - assets/cast3.jpeg
    - assets/cast4.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
